Document: uselessd
Title: Debian uselessd Manual
Author: <insert document author here>
Abstract: This manual describes what uselessd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/uselessd/uselessd.sgml.gz

Format: postscript
Files: /usr/share/doc/uselessd/uselessd.ps.gz

Format: text
Files: /usr/share/doc/uselessd/uselessd.text.gz

Format: HTML
Index: /usr/share/doc/uselessd/html/index.html
Files: /usr/share/doc/uselessd/html/*.html
